// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQACfSaTr8IFRgoEjAau7nLCSSIhBnf4I',
    appId: '1:87280940664:web:d8f193e63b0eed907b1f8d',
    messagingSenderId: '87280940664',
    projectId: 'brew-a6cab',
    authDomain: 'brew-a6cab.firebaseapp.com',
    storageBucket: 'brew-a6cab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa517EplxO2iabY6Q47dKZ6bSrfQGk4Cg',
    appId: '1:87280940664:android:ee869e1bf9489d7a7b1f8d',
    messagingSenderId: '87280940664',
    projectId: 'brew-a6cab',
    storageBucket: 'brew-a6cab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN5UQcdlatUGeWX_xjv00vT1gfhE-JsJo',
    appId: '1:87280940664:ios:779055d84a73dcc37b1f8d',
    messagingSenderId: '87280940664',
    projectId: 'brew-a6cab',
    storageBucket: 'brew-a6cab.appspot.com',
    iosClientId: '87280940664-89f98ig67vf4cihbp67eiun7il88dnqq.apps.googleusercontent.com',
    iosBundleId: 'com.mirolic.brew',
  );
}
